apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      tier: backend
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: shunya7/uber-auth-service:v1
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: CLOUD_SERVICE
              value: "cloud-service-service"
          resources:
            requests: 
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "300m" 