apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-service-deployment
  labels:
    app: cloud-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-service
      tier: backend
  template:
    metadata:
      labels:
        app: cloud-service
        tier: backend
    spec:
      containers:
        - name: cloud-service
          image: shunya7/uber-cloud-service:v1
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "300m"
        