apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service-deployment
  labels:
    app: location-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
      tier: backend
  template:
    metadata:
      labels:
        app: location-service
        tier: backend
    spec:
      containers:
        - name: location-service
          image: shunya7/uber-location-service:v1
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: CLOUD_SERVICE
              value: "cloud-service-service"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "300m"