apiVersion: v1
kind: Service
metadata:
  name: review-service-service
  labels:
    app: review-service
    tier: backend
spec:
  selector:
    app: review-service
    tier: backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: NodePort