apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: uber-kafka-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: uber-kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral